syntax = "proto3";

package io.github.twyora.douyinenhancer.hook;

option java_outer_classname = "Configs";
option java_package = "io.github.twyora.douyinenhancer.hook";
option optimize_for = LITE_RUNTIME;

message Class {
  optional string name = 1;
}

message Method {
  optional string name = 1;

  message Parameters {
    repeated string values = 1;
  }
  optional Parameters parameters = 2;
}

message Field {
  optional string name = 1;
}

message Comment {
  optional Class class = 1;
  optional Field emoji = 2;
  optional Field image_list = 3;
  optional Field comment_audio = 4;
}

message CommentAudioStruct {
  optional Class class = 1;
  optional Field content = 2;
}

message CommentImageStruct {
  optional Class class = 1;
  optional Field origin_url = 2;
  optional Field download_url = 3;
  optional Method get_download_url = 4;
}

message Emoji {
  optional Class class = 1;
  optional Method animate_url = 2;
}

message UrlModel {
  optional Class class = 1;
  optional Field url_list = 2;
}

message CommentActionParams {
  optional Class class = 1;
  optional Field comment = 2;
}

message CommentLongPressItemModel {
  optional Class class = 1;
  optional Field comment_action_params = 2;
}

message SaveImageActionItem {
  optional Class class = 1;
  optional Method is_visible = 5;
  optional Method on_click = 6;

  reserved 2, 3, 4;
}

message DigestUtils {
  optional Class class = 1;
  optional Method md5_hex = 2;
}

message DownloadInfo {
  optional Class class = 1;
  optional Field url = 2;
  optional Method get_target_file_path = 3;
}

message UGFileUtilsKt {
  optional Class class = 1;
  optional Field context = 2;
  optional Method copy_file = 3;
  optional Method get_storage_dir = 4;
  optional Method get_external_storage_dir = 5;
  optional Method get_image_uri = 6;
  optional Method create_uri = 7;
  optional Method get_audio_uri = 8;
}

message ListenerProviderParam {
  optional Class class = 1;
  optional Field context = 2;
  optional Field cert = 3;
}

message CommentImageSaveDownloadListener {
  optional Class class = 1;
  optional Method on_successed = 2;
  optional Method notify_result = 3;
  optional Field listener_provider_param = 4;
}

message CommonItemView {
  optional Class class = 1;
  optional Method set_left_text = 2;
  optional Method set_right_ui_mode = 3;
  optional Method set_left_icon = 4;
  optional Method set_right_text = 5;
  reserved 6;
}

message DouYinSettingNewVersionActivity {
  optional Class class = 1;
  optional Field settings_scroll_view = 2;
  optional Method on_resume = 3;
}

message User {
  optional Class class = 1;
  optional Field nickname = 2;
  optional Field uid = 3;
}

message AwemeStatistics {
  optional Class class = 1;
  optional Field collect_count = 2;
  optional Field comment_count = 3;
  optional Field digg_count = 4;
  optional Field share_count = 5;
}

message Aweme {
  optional Class class = 1;
  optional Field desc = 2;
  optional Field author = 3;
  optional Method get_ad = 4;
  optional Field item_title = 5;
  optional Field duration = 6;
  optional Method is_normal_video = 7;
  optional Method is_ecom_aweme = 8;
  optional Field groupon_large_card = 9;
  optional Method is_live = 10;
  optional Method is_multi_image = 11;
  optional Method get_video = 12;
  optional Field images = 13;
  optional Field statistics = 14;
  optional Method get_aid = 15;
  optional Method get_download_status = 16;
  optional Field aid = 17;
  optional Field status = 18;
}

message AwemeStatus {
  optional Class class = 1;
  optional Field download_status = 2;
}

message Video {
  optional Class class = 1;
  optional Method get_play_addr = 2;
  optional Field has_suffix_water_mark = 3;
  optional Field has_water_mark = 4;
  optional Field download_addr = 5;
}

message ImageUrlStruct {
  optional Class class = 1;
  optional Field watermark_free_download_url_list = 2;
  optional Field url_list = 3;
  optional Field download_url_list = 4;
  optional Field video = 5;
}

message FeedResponseHandler {
  optional Class class = 1;
  optional Method processAwemeList = 2;
}

message CommentLongPressWhiteListProvider {
  optional Class class = 1;
  optional Method buildWhiteList = 2;
}

message MiscDownloadAddrUtil {
  optional Class class = 1;
  optional Method get_suffix_scene_download_addr = 2;
}

message DownloadAction {
  optional Class class = 1;
  optional Method start_download = 2;
  optional Field aweme = 3;
}

message ABTestServiceImpl {
  optional Class class = 1;
  optional Method enable_save_image_to_video_local_water_mask = 2;
  optional Method enable_ve_add_live_video_water_mark = 3;
}

message HeifDecoder {
  optional Class class = 1;
  optional Field s_bitmap_factory = 2;
}

message HeifBitmapFactoryImpl {
  optional Class class = 1;
  optional Method decode_byte_array = 2;
}

message DownLoadExecutor {
  optional Class class = 1;
  optional Method execute = 2;
}

message DownLoadTask {
  optional Class class = 1;
  optional Method get_target_file_paths = 2;
}

message DownloadLivePhotoExecutor {
  optional Class class = 1;
  optional Method encode_live_photo = 2;
}

message SingleImageToMp4Composer {
  optional Class class = 1;
  optional Method on_load = 2;
}

message MultiImageToMp4Composer {
  optional Class class = 1;
  optional Method on_load = 2;
  optional Field image_path_list = 3;
}

message AbsPermissionChecker {
  optional Class class = 1;
  optional Method get_action_check_result = 2;
}

message ActionCheckResult {
  optional Class class = 1;
  optional Field action_status = 2;
}

message ActionStatus {
  optional Class class = 1;
  optional Field grayed = 3;
  optional Field hidden = 4;
  optional Field normal = 5;

  reserved 2;
}

message GalleryShareHelper {
  optional Class class = 1;
  optional Method start_download = 2;
}

message SharePrivacyVideoApi {
  optional Class class = 1;
  optional SharePrivacyVideoResponse privacy_video_response = 2;
  optional Method getDownloadStatus = 3;
}

message SharePrivacyVideoResponse {
  optional Class class = 1;
  optional Field msg = 2;
  optional Field status = 3;
}

message RxObservable {
  optional Class class = 1;
  optional Method just = 2;
}

message ListenAwemeFilter {
  optional Class class = 1;
  optional Method accept = 2;
}

message MainActivity {
  optional Class class = 1;
  optional Method on_resume = 2;
  optional Method on_new_intent = 3;
}

message BaseListFragmentPanel {
  optional Class class = 1;
  optional Method handle_double_click = 2;
  optional Method handle_video_event = 3;
  optional Method get_current_aweme = 4;
  optional Method pause_current_player_with_listener = 5;
  optional Method show_iv_when_pause = 6;
  optional Method on_video_player_event = 7;
}

message VideoPlayerEvent {
  optional Class class = 1;
  optional Field code = 2;
}

message FluxComponentId {
  optional Class class = 1;
  optional Field music_cover_block = 2;
  optional Field music_listen_cover = 3;
  optional Field digg = 4;
  optional Field title = 5;
  optional Field music_cover = 6;
  optional Field general_label = 7;
  optional Field feed_label_container = 8;
  optional Field music_title = 9;
  optional Field story_25_diverse_digg = 10;
  optional Field ecom_store = 11;
  optional Field button_im_quick_share = 12;
  optional Field button_feed_im_share_guide_v2 = 13;
  optional Field button_force_feed_im_share_guide = 14;
  optional Field social_new_comment_guide_bubble = 15;
  optional Field comment_bottom_animation = 16;
  optional Field nearby_identity_tag = 17;
  optional Field live_photo_tag = 18;
  optional Field photos_tag = 19;
  optional Field story24_tag = 20;
  optional Field social_new_style_story_tag = 21;
  optional Field long_video_highlight_tag = 22;
  optional Field danmaku_vertical = 23;
  optional Field avatar = 24;
  optional Field nickname = 25;
  optional Field post_time = 26;
  optional Field bellow_desc_time = 27;
  optional Field comment = 28;
  optional Field reply = 29;
  optional Field share = 30;
  optional Field collect = 31;
  optional Field anchor_framework = 32;
  optional Field bottom_bar_common = 33;
  optional Field common_button = 34;
  optional Field sticker = 35;
  optional Field ai_search = 36;
  optional Field c2_feed = 37;
  optional Field flow = 38;
  optional Field nearby_hot_comment = 39;
  optional Field button_unfollow_familiar = 40;
  optional Field button_unfollow_familiar_rec = 41;
  optional Field co_creator_author = 42;
  optional Field chapter_tag = 43;
  optional Field ecom_tag_friend = 44;
  optional Field social_new_style_post_time_bottom = 45;
  optional Field social_new_style_music_below = 46;
  optional Field chapter_detail = 47;
  optional Field title_tag_container = 48;
  optional Field right_menu_ll = 49;
  optional Field music_mute_cover = 50;
  optional Field jx_left_bottom_long_video_plus_title_tag = 51;
  optional Field bottom_bar_mix = 52;
  optional Field bottom_bar_normal_search = 53;
  optional Field bottom_bar_common_priority_search = 54;
  optional Field jx_pick = 55;
  optional Field bottom_bar_container = 56;
  optional Field ai_co_creators_three = 57;
  optional Field aigc_cocreate_status_title = 58;
}

message FluxComponentDataAction {
  optional Class class = 1;
  optional Method get_set = 2;
}

message VideoEvent {
  optional Class class = 1;
  optional Field video_type = 2;
}

message CleanModePresenter {
  optional Class class = 1;
  optional Method enter_clean_mode = 2;
  optional Method set_visibility = 3;
}

message DanmakuView {
  optional Class class = 1;
  optional Method on_attached_to_window = 2;
}

message HookInfo {
  uint64 last_update_time = 1;
  uint32 module_version_code = 2;
  string module_version_name = 3;
  uint32 host_version_code = 4;
  uint32 generation = 5;

  optional CommentImageStruct comment_image_struct = 6;
  optional UrlModel url_model = 7;
  optional Comment comment = 8;
  optional Emoji emoji = 9;
  optional CommentActionParams comment_action_params = 10;
  optional CommentLongPressItemModel comment_long_press_item_model = 11;
  optional SaveImageActionItem save_image_action_item = 12;
  optional CommentImageSaveDownloadListener comment_image_save_download_listener = 14;
  optional DownloadInfo download_info = 15;
  optional DigestUtils digest_utils = 16;
  optional UGFileUtilsKt ug_file_utils = 17;
  optional CommonItemView common_item_view = 19;
  optional DouYinSettingNewVersionActivity dou_yin_setting_new_version_activity = 20;
  optional User user = 21;
  optional Aweme aweme = 22;
  optional FeedResponseHandler feed_response_handler = 23;
  optional CommentLongPressWhiteListProvider comment_long_press_white_list_provider = 24;
  optional CommentAudioStruct comment_audio_struct = 25;
  optional ListenerProviderParam listener_provider_param = 26;
  optional MiscDownloadAddrUtil misc_download_addr_util = 27;
  optional Video video = 28;
  optional DownloadAction download_action = 29;
  optional ImageUrlStruct image_url_struct = 30;
  optional ABTestServiceImpl ab_test_service_impl = 31;
  optional AwemeStatistics aweme_statistics = 33;
  optional HeifDecoder heif_decoder = 35;
  optional HeifBitmapFactoryImpl heif_bitmap_factory_impl = 36;
  optional DownLoadExecutor down_load_executor = 37;
  optional DownLoadTask down_load_task = 38;
  optional SingleImageToMp4Composer single_image_to_mp4_composer = 39;
  optional MultiImageToMp4Composer multi_image_to_mp4_composer = 40;
  optional DownloadLivePhotoExecutor download_live_photo_executor = 41;
  optional MainActivity main_activity = 42;
  optional AbsPermissionChecker abs_permission_checker = 43;
  optional ActionCheckResult action_check_result = 44;
  optional ActionStatus action_status = 45;
  optional GalleryShareHelper gallery_share_helper = 46;
  optional AwemeStatus aweme_status = 47;
  optional SharePrivacyVideoApi share_privacy_video_api = 48;
  optional RxObservable rx_observable = 49;
  optional ListenAwemeFilter listen_aweme_filter = 50;
  optional BaseListFragmentPanel base_list_fragment_panel = 51;
  optional VideoEvent video_event = 52;
  optional CleanModePresenter clean_mode_presenter = 53;
  optional DanmakuView danmaku_view = 54;
  optional VideoPlayerEvent video_player_event = 55;
  optional FluxComponentId flux_component_id = 56;
  optional FluxComponentDataAction flux_component_data_action = 57;

  reserved 13, 18, 32;
}
