name: Spotless Format Check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/src/**'
      - '**.gradle'
      - '**.gradle.kts'
      - 'gradle.properties'

permissions:
    contents: read

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Spotless Check
        run: bash ./gradlew spotlessCheck
